import React, { createRef, useCallback } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Form } from '@unform/web';
import Link from 'next/link';
import { FormHandles } from '@unform/core';

import api from '../../../services/api';
import { IUserDTO } from '../../../interfaces/dtos/IUserDTO';
import Input from '../../../components/Input';
import containerStyle from '../../../styles/Container.module.css';
import formStyle from '../../../styles/Form.module.css';
import buttonStyle from '../../../styles/Button.module.css';

const CreateUser: NextPage = () => {
  const formRef = createRef<FormHandles>();

  const handleSubmitCreateUser = useCallback(
    async ({ name, email, country }: IUserDTO) => {
      api.post('api/users', { name, email, country });

      formRef.current?.setData({
        name: '',
        email: '',
        country: '',
      });
    },
    [formRef],
  );

  return (
    <div className={containerStyle.container}>
      <Head>
        <title>CRUD Next com mongoDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Create user</h1>
      <Form
        onSubmit={event => handleSubmitCreateUser(event)}
        ref={formRef}
        className={formStyle.form}
      >
        <Input type="text" placeholder="nome" name="name" />
        <Input type="text" placeholder="email" name="email" />
        <Input type="text" placeholder="estado" name="country" />
        <button type="submit" className={buttonStyle.button}>
          Enviar
        </button>
      </Form>
      <Link href="/users">
        <a>Voltar para a tabela de usuáros</a>
      </Link>
    </div>
  );
};

export default CreateUser;
