import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CRUD Next com mongoDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>CRUD utilizando Next, MongoDB e Typescript!</h1>
      <Link href="/users">
        <a>Ir para a tabela de usuáros</a>
      </Link>
      <Link href="/users/create">
        <a>Criar novo usuáro</a>
      </Link>
    </div>
  );
};

export default Home;
