import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { Form } from '@unform/web';
import Input from '../../components/Input';
import { createRef, useCallback } from 'react';
import api from '../../services/api';
import { FormHandles } from '@unform/core';

interface IStoreUserSubmit {
  name: string;
  email: string;
  country: string;
}

const StoreUser: NextPage = () => {
  const formRef = createRef<FormHandles>();

  const handleSubmitStoreUser = useCallback(
    async ({ name, email, country }: IStoreUserSubmit) => {
      api.post('api/users', { name, email, country });

      formRef.current?.setData({
        name: '',
        email: '',
        country: '',
      });
    },
    [formRef],
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>CRUD Next com mongoDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Create user</h1>
      <Form onSubmit={event => handleSubmitStoreUser(event)} ref={formRef}>
        <Input type="text" placeholder="nome" name="name" />
        <Input type="text" placeholder="email" name="email" />
        <Input type="text" placeholder="estado" name="country" />
        <button type="submit">Enviar</button>
      </Form>
    </div>
  );
};

export default StoreUser;
